educ_finance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from xauth import views as xauth_views


MEDIA_ROOT = getattr (settings,"MEDIA_ROOT")
MEDIA_URL = getattr (settings,"MEDIA_URL")


urlpatterns = [
    path('', views.RedirectionView.as_view(),name='redirect'),
    path('home/', views.IndexTemplateView.as_view(),name='index-view'),
    path('admin/', admin.site.urls),
    path("import-export/", include("ie_app.urls")),
    path('login/', xauth_views.CustomLoginView.as_view(), name='user-login'),
    path('logout/', xauth_views.CustomLogoutView.as_view(), name='user-logout'),
    path("signup/", xauth_views.User2CreateView.as_view(), name="user-signup"),
    path(
        "account-activation/<uuid:pk>/set-password/",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path(
        "account-activation/<str:uidb64>/set-password/<str:token>",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path('auth/', include('xauth.urls')),
    path('parameter/', include('parameter.urls')),   
    path('management/', include('gestion_administratif.urls')), 
    path('finance/', include('gestion_finance.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

gestion_administratif/urls.py
from django.urls import path
from . import views
from gestion_administratif.views import HistoriqueDossier
from .views import StatistiquesView

app_name = "gestion_administratif"

urlpatterns = [
    path('dossiers/', views.DossierListView.as_view(), name='dossier-list'),
    path('dossiers/create/', views.DossierCreateView.as_view(), name='dossier-create'),
    path('dossiers/<uuid:pk>/', views.DossierDetailView.as_view(), name='dossier-detail'),
    path('dossiers/<uuid:pk>/update/', views.DossierUpdateView.as_view(), name='dossier-update'),
    path('dossiers/<uuid:pk>/delete/', views.DossierDeleteView.as_view(), name='dossier-delete'),
    path('dossier/<uuid:pk>/<str:action>/', views.valider_ou_rejeter_dossier, name='valider_ou_rejeter_dossier'),
    path('transfert/<uuid:pk>/', views.Transfert.as_view(), name='transfert-dossier'),
    path('dossiers-transferes/', HistoriqueDossier.as_view(), name='historique-dossier'),
    
    

    path('statistiques/', StatistiquesView.as_view(), name='statistiques')
    
]

# urls.py

gestion_finance/urls.py
# gestion_finance/urls.py

from django.urls import path
from . import views
from .views import PrintReceiptView



app_name = 'gestion_finance'

urlpatterns = [
    path('other/valider/', views.ValiderPaiement, name='valider'),
    path('paiements/list', views.PaiementListView.as_view(), name='paiement-list'),
    path('paiements/create/', views.PaiementCreateView.as_view(), name='paiement-create'),
    path('paiements/<uuid:pk>/', views.PaiementDetailView.as_view(), name='paiement-detail'),
    path('paiements/<uuid:pk>/update/', views.PaiementUpdateView.as_view(), name='paiement-update'),
    path('paiements/<uuid:pk>/delete/', views.PaiementDeleteView.as_view(), name='paiement-delete'),
    
    #path('Paiement/<uuid:pk>/<str:action>/', views.valider_ou_rejeter_Paiement, name='valider_ou_rejeter_Paiement'),
    path('paiement/dossier/list', views.DossierValideListView.as_view(), name='dossier-list'),
    path('paiements/create/<uuid:pk>', views.DossierPaiementCreateView.as_view(), name='dossier-paiement'),
    path('paiements/<uuid:pk>/recu/', PrintReceiptView.as_view(), name='print_receipt'),    
]

xauth/urls.py
from django.urls import path

from xauth import views

app_name = "auth"

urlpatterns = [
    # User
    path("users/create/", views.UserCreateView.as_view(), name="user-create"),
    path("users/list/", views.UserListView.as_view(), name="user-list"),
    path("users/staff/list/", views.StaffListView.as_view(), name="staff-list"),
    path(
        "users/<uuid:pk>/edit/",
        views.UserUpdateView.as_view(),
        name="user-update",
    ),
    path(
        "users/<uuid:pk>/edit/photo",
        views.UserProfilePhotoUpdateView.as_view(),
        name="user-update-photo",
    ),
    path(
        "users/<uuid:pk>/detail/",
        views.UserDetailView.as_view(),
        name="user-detail",
    ),
    path(
        "users/<uuid:pk>/delete/",
        views.UserDeleteView.as_view(),
        name="user-delete",
    ),
    path(
        "users/<uuid:pk>/password/",
        views.UserUpdatePasswordView.as_view(),
        name="user-update-password",
    ),
    path(
        "users/<uuid:pk>/make-admin/",
        views.UserAdminRightView.as_view(),
        name="user-make-admin",
    ),
    path(
        "users/<uuid:pk>/send-activation-key/",
        views.UserSendSecreteKey.as_view(),
        name="user-send-key",
    ),
    # Group
    path("groups/create/", views.GroupCreateView.as_view(), name="group-create"),
    path(
        "groups/<int:pk>/update/",
        views.GroupUpdateView.as_view(),
        name="group-update",
    ),
    path("groups/list/", views.GroupListView.as_view(), name="group-list"),
    path(
        "groups/<int:pk>/delete/",
        views.GroupDeleteView.as_view(),
        name="group-delete",
    ),
    path(
        "groups/<int:pk>/detail/",
        views.GroupDetailView.as_view(),
        name="group-detail",
    ),
    # Assign
    # path(
    #     "users/nomination/<uuid:pk>/create/",
    #     views.AssignCreateView.as_view(),
    #     name="nomination-create",
    # ),
    path(
        "users/nomination/<uuid:pk>/create/",
        views.RoleCreateView.as_view(),
        name="nomination-create",
    ),
    path('activity/', views.ActivityLogView.as_view(), name='activity_log'),
]

gestion_finance/models.py
from django.db import models
from educ_finance.cmodels import CommonAbstractModel


class Paiement(CommonAbstractModel):
    
    
    STATUS_CHOICES = [
        ('initie', 'Initié'),
        ('partiellement payé', 'Partiellement payé'),
        ('soldé', 'Soldé'),
    ]
    
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='initie',
        verbose_name="Statut"
    )
    
    reference = models.CharField(
        max_length=20, 
        unique=True, 
        verbose_name="Référence", 
        null=True
    )
    dossier = models.ForeignKey(
        'gestion_administratif.Dossier', 
        on_delete=models.CASCADE, 
        verbose_name="Dossier enseignant", 
        help_text="Dossier de l'enseignant associé", 
        null=True,
        related_name="paiements"
        
    )
    montant_total_a_verser = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        verbose_name="Montant total", 
        null=True
    )
    date_paiement = models.DateField(
        verbose_name="Date de paiement", 
        null=True
    )
    montant_verser = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        verbose_name="Montant versé", 
        null=True
    )
    montant_restant_a_verser = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        verbose_name="Montant restant", 
        editable=False,  # Rend le champ non éditable via l'interface d'administration
        null=True
    )
    is_tranche = models.BooleanField(
        default=False, 
        verbose_name="Paiement par tranche"
    )
    
    is_tranfered = models.BooleanField(default=False, verbose_name="Transféré")
    
    type_paiement = models.ForeignKey(
        'parameter.TypePaiement', 
        on_delete=models.CASCADE, 
        verbose_name="Type de Paiement", 
        help_text="Type de paiement associé", 
        null=True
    )
    dossier = models.ForeignKey('gestion_administratif.dossier', on_delete=models.CASCADE, verbose_name="Dossier enseignant", 
    help_text="Dossier de l'enseignant associé", null=True)

    def save(self, *args, **kwargs):
        """
        Calcule automatiquement le montant restant à payer avant de sauvegarder l'instance.
        """
        if self.montant_total_a_verser is not None and self.montant_verser is not None:
            self.montant_restant_a_verser = self.montant_total_a_verser - self.montant_verser
        super().save(*args, **kwargs)  # Appelle la méthode `save` de la classe parente

    def __str__(self):
        return f"{self.reference} - {self.dossier}"

gestion_finance/views.py

from django.shortcuts import render
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from gestion_administratif.models import Dossier
from educ_finance.views import (
    CustomCreateView,
    CustomDeleteView,
    CustomDetailView,
    CustomListView,
    CustomUpdateView,
)
from formset.views import FileUploadMixin
from .forms import PaiementForm, PaiementPartielleForm
from .models import Paiement
from django.views import View
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse
from django.contrib.auth.models import User
from parameter.models import TypePaiement

from django.http import HttpResponse
from django.template.loader import render_to_string
from django_weasyprint import WeasyTemplateResponseMixin
from django_weasyprint.views import WeasyTemplateResponse
from django_weasyprint.utils import django_url_fetcher
from weasyprint import HTML


import tempfile



# Create your views here.
#finis

class PaiementListView(CustomListView):
    model = Paiement
    name = "paiement"
    template_name = "list-finance.html"
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["can_delete"] = False
        context["can_add"] = False
        context["can_update"] = False
        context["add_url"] = reverse_lazy("gestion_finance:paiement-create")
        return context


class PaiementCreateView(CustomCreateView):
    model = Paiement
    form_class = PaiementForm
    name = "paiement"
    success_url = reverse_lazy("gestion_finance:paiement-list")


class PaiementUpdateView(FileUploadMixin, CustomUpdateView):
    
    model = Paiement
    name = "paiement"
    form_class = PaiementForm
    template_name = "components/ufr_form.html"

    success_url = reverse_lazy("gestion_finance:paiement-list")


class PaiementDetailView(CustomDetailView):
    model = Paiement
    name = "paiement"
    template_name = "detail-finance.html"
    success_url = reverse_lazy("gestion_finance:paiement-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["card_title"] = "Détails du Paiement"
        context["update_url"] = "gestion_finance:paiement-update"
        context["delete_url"] = "gestion_finance:paiement-delete"
        context["list_url"] = "gestion_finance:paiement-list"
        return context


class PaiementDeleteView(CustomDeleteView):
    model = Paiement
    name = "paiement"
    template_name ="delete-finance.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        object = self.get_object()  # Utilisation de self.get_object()
        context["card_title"] = f"Suppression de dossier"  # Affichage du sigle
        context["list_url"] = reverse_lazy("gestion_finance:paiement-list")  # URL du retour
        context["list_of"] = "Suppression de dossier"
        return context
    

class DossierValideListView(CustomListView):
    model = Dossier
    name = "dossier"
    template_name = "list-finance1.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["can_delete"] = False
        context["can_add"] = False
        context["can_import"] = False
        context["can_update"] = False
        context["can_delete"] = False
        context["object_list_en_cours"] = Dossier.objects.filter(is_tranfered =True, status = "initie")
        context["object_list_transferes"] = Dossier.objects.filter(status = "partiellement payé")
        print(context["object_list_transferes"])
        context["object_list_solde"] = Paiement.objects.filter(montant_restant_a_verser=0)
        context["type_paiement_list"] = TypePaiement.objects.all() 
        return context
    
    
# def DossierPaiementCreateView(View):
#     def post(self, form):
#         id = self.kwargs.get("pk")
#         dossier = get_object_or_404(Dossier, pk=id)
#         form.instance.dossier = dossier
#         return super().form_valid(form)


def ValiderPaiement(request):
    reference = request.POST.get("reference")
    montant_total_a_verser = request.POST.get("montant_total_a_verser")
    montant_verser = request.POST.get("montant_verser")
    date_paiement = request.POST.get("date_paiement")
    type_paiement = request.POST.get("type_paiement")
    dossier_id = request.POST.get("dossier_id")

    dossier = Dossier.objects.filter(id = dossier_id).first()
    type = TypePaiement.objects.filter(id = type_paiement).first()
    
    if not (reference and montant_total_a_verser and montant_verser and date_paiement and type_paiement):
        return redirect("gestion_finance:paiement-list")
    if dossier.status == "initie":
        paiement = Paiement.objects.create(
        dossier=dossier,
        reference=reference,
        montant_total_a_verser=float(montant_total_a_verser),
        montant_verser=float(montant_verser),
        date_paiement=date_paiement,
        type_paiement=type,
        )
        dossier.montant = montant_total_a_verser
        
    elif dossier.status == "partiellement payé":
        pass
    
    dossier.is_payed = True
    dossier.save()
    paiement = Paiement.objects.create(
        dossier=dossier,
        reference=reference,
        montant_total_a_verser=float(montant_total_a_verser),
        montant_verser=float(montant_verser),
        date_paiement=date_paiement,
        type_paiement=type,
        )
    return redirect("gestion_finance:paiement-list")


class DossierPaiementCreateView(CustomCreateView):
    print(2)
    model = Paiement
    form_class = PaiementForm
    name = "paiement"
    success_url = reverse_lazy("gestion_finance:paiement-list")
    
    def get_form_class(self):
        id = self.kwargs.get("pk")
        dossier = get_object_or_404(Dossier, pk=id)
        print(dossier.status)
        if dossier.status == "initie":
            return PaiementForm
        elif dossier.status == "partiellement payé":
            return PaiementPartielleForm
    
    def form_valid(self, form):
        id = self.kwargs.get("pk")
        dossier = get_object_or_404(Dossier, pk=id)
        is_tranche = form.cleaned_data['is_tranche']
        
        if dossier.status == "initie":
            if is_tranche is 'm' :
                is_tranche = False
                form.instance.montant_restant_a_verser = 0 
                form.instance.montant_verser =  form.cleaned_data['montant_total_a_verser']
                dossier.montant = form.cleaned_data['montant_total_a_verser']
                dossier.status = "soldé"
            elif is_tranche is 'f':
                is_tranche = True
                form.instance.montant_restant_a_verser = form.cleaned_data['montant_total_a_verser'] - form.cleaned_data['montant_verser']
                form.instance.montant_verser =  form.cleaned_data['montant_verser']
                dossier.montant = form.cleaned_data['montant_total_a_verser']
                dossier.reste_a_payer = form.cleaned_data['montant_total_a_verser'] - form.cleaned_data['montant_verser']
                dossier.status = "partiellement payé"
            dossier.montant = form.cleaned_data['montant_total_a_verser']
        elif dossier.status == "partiellement payé":
            if is_tranche is 'm' :
                is_tranche = False
                form.instance.montant_restant_a_verser = 0 
                form.instance.montant_verser =  form.cleaned_data['montant_total_a_verser']
            elif is_tranche is 'f':
                is_tranche = True
                form.instance.montant_restant_a_verser = form.cleaned_data['montant_total_a_verser'] - form.cleaned_data['montant_verser']
                form.instance.montant_verser =  form.cleaned_data['montant_verser']
                dossier.montant = dossier.reste_a_payer - form.cleaned_data['montant_verser']
                dossier.status = "soldé"
        dossier.is_payed = True
        dossier.save()
        form.instance.is_tranche = is_tranche
        form.instance.dossier = dossier
        return super().form_valid(form)



from django.http import HttpResponse
from django.template.loader import render_to_string
from django.views.generic.detail import DetailView
from weasyprint import HTML
import os
import tempfile
from django.template.loader import render_to_string
import weasyprint


#    
class PrintReceiptView(WeasyTemplateResponseMixin, CustomDetailView):
    model = Paiement  # Modèle correspondant
    template_name = 'recu.html'

    def get_pdf_filename(self):
        paiement = self.get_object()
        return f"recu-{paiement.reference}.pdf"

    # def render_to_response(self, context, **response_kwargs):
    #     html = render_to_string(self.template_name, context)
        
    #     pdf = weasyprint.HTML(string=html).write_pdf()

    #     response = HttpResponse(pdf, content_type='application/pdf')
    #     response['Content-Disposition'] = f'attachment; filename="{self.get_pdf_filename()}"'
    #     return response


    
    

gestion_finance/templates/delete-finance.html
{% extends "bases/base.html" %}

{% block title %} {{ title }} {% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{{ list_url }}">{{ list_of }}</a></li>
<li class="breadcrumb-item active" aria-current="page"><strong>Suppression - {{ what_of }}</strong></li>
{% endblock breadcrumb %}

{% block content %}
<div class="container-fluid">
    <div class="card p-5">
        <!-- En-tête avec le titre de la carte -->
        <div class=""> 
            <div class="card">
                <div class="card-header">
                    <h2 class=" text-dark fw-bold m-0">{{ card_title }}</h2>
                </div>
            </div>
            
        </div>
        

        <!-- Bouton retour en haut à droite -->
        
        <!-- Message d'avertissement et confirmation de suppression -->
        <div class="card-body">
            
            <div class="d-flex justify-content-end ">
                <a href="{{ list_url }}" class="btn btn-outline-secondary btn-sm d-inline-flex align-items-center" data-bs-toggle="tooltip" title="Retour à la liste">
                    <i class="fas fa-arrow-left me-2"></i> Retour
                </a>
            </div>

            <div class="alert">
                <p>{{ message }}</p>
                {{ form.as_p }}
                
                <p>
                    Êtes-vous sûr(e) de vouloir supprimer "{{ what_to }} : {{ what_of }}" ?<br>
                    <span class="text-danger">Cette action est irréversible.</span>
                </p>
            </div>
            

            <!-- Formulaire de confirmation de suppression -->
            <form method="post" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-lg btn-danger px-5 py-2" style="border-radius: 8px;">
                    <i class="fas fa-trash-alt me-2"></i> Confirmer la suppression
                </button>
            </form>
        </div>

        <!-- Bas de la carte pour un espacement visuel agréable -->
        <div class="p-3"></div>
    </div>
</div>

<script>
    // Initialiser le tooltip
    document.querySelectorAll('[data-bs-toggle="tooltip"]').forEach(function (tooltipTriggerEl) {
        new bootstrap.Tooltip(tooltipTriggerEl);
    });
</script>
{% endblock content %}

gestion_finance/templates/dossier_trans.html
{% extends "bases/base.html" %}
{% load icon %}

{% block breadcrumb %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h2>{{ card_title }}</h2>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">{{ list_of }}</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">{{ card_title }}</a></li>
        </ol>
    </div>
</div>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card pt-4">
            <div class="card-body">
                <!-- Barre de recherche et outils -->
                <div class="d-flex flex-row mb-5 justify-content-between">
                    <div>
                        {% include "components/searchbar.html" %}
                    </div>
                    <div>
                        {% block toolbar %}
                        {% include "components/toolbar.html" %}
                        {% block toolbar-plus %}{% endblock toolbar-plus %}
                        {% endblock toolbar %}
                    </div>
                </div>

                <!-- Onglets Bootstrap -->
                <ul class="nav nav-tabs nav-fill mb-4" id="dossierTabs" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="en-cours-tab" data-bs-toggle="tab" data-bs-target="#en-cours-pane" type="button" role="tab" aria-controls="en-cours-pane" aria-selected="true">
                            PAIEMENT EN COURS
                        </button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="payes-tab" data-bs-toggle="tab" data-bs-target="#payes-pane" type="button" role="tab" aria-controls="payes-pane" aria-selected="false">
                            PAIEMENT AVANCÉ
                        </button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="solde-tab" data-bs-toggle="tab" data-bs-target="#solde-pane" type="button" role="tab" aria-controls="solde-pane" aria-selected="false">
                            PAIEMENT SOLDÉ
                        </button>
                    </li>
                </ul>

                <!-- Contenu des Onglets -->
                <div class="tab-content" id="dossierTabContent">
                    <!-- Tab Dossiers en cours -->
                    <div class="tab-pane fade show active" id="en-cours-pane" role="tabpanel" aria-labelledby="en-cours-tab">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th class="text-center">#</th>
                                        {% block table-headers-en-cours %}{% endblock table-headers-en-cours %}
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for object in object_list_en_cours %}
                                    <tr>
                                        <th scope="row" class="text-center">{{ forloop.counter }}</th>
                                        {% block table-rows-en-cours %}{% endblock table-rows-en-cours %}
                                        <td class="text-center">
                                            <div class="btn-group" role="group" aria-label="Options">
                                                {% block list-options-en-cours %}
                                                <button type="button" class="btn btn-outline-success" data-bs-id="{{ object.id }}" data-bs-toggle="modal" data-bs-target="#transfert-{{ object.id }}">
                                                    {% icon "arrow-right" height="16px" width="16px" %} Transférer
                                                </button>
                                                {% endblock list-options-en-cours %}
                                            </div>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="20" class="text-center">Aucun enregistrement</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- Tab Dossiers payés -->
                    <div class="tab-pane fade" id="payes-pane" role="tabpanel" aria-labelledby="payes-tab">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th class="text-center">#</th>
                                        {% block table-headers-payes %}{% endblock table-headers-payes %}
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for object in object_list_transferes %}
                                    <tr>
                                        <th scope="row" class="text-center">{{ forloop.counter }}</th>
                                        {% block table-rows-payes %}{% endblock table-rows-payes %}
                                        <td class="text-center">
                                            <div class="btn-group" role="group" aria-label="Options">
                                                {% block list-options-payes %}
                                                <a href="{% url 'gestion_administratif:dossier-detail' object.id %}">
                                                    <button type="button" class="btn btn-outline-primary">
                                                        {% icon "eye" height="16px" width="16px" %} Voir
                                                    </button>
                                                </a>
                                                {% endblock list-options-payes %}
                                            </div>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="20" class="text-center">Aucun enregistrement</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- Tab Dossiers soldés -->
                    <div class="tab-pane fade" id="solde-pane" role="tabpanel" aria-labelledby="solde-tab">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th class="text-center">#</th>
                                        {% block table-headers-solde %}{% endblock table-headers-solde %}
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for object in object_list_solde %}
                                    <tr>
                                        <th scope="row" class="text-center">{{ forloop.counter }}</th>
                                        {% block table-rows-solde %}{% endblock table-rows-solde %}
                                        <td class="text-center">
                                            <div class="btn-group" role="group" aria-label="Options">
                                                {% block list-options-solde %}
                                                <a href="{% url 'gestion_finance:paiement-detail' object.id %}">
                                                    <button type="button" class="btn btn-outline-success">
                                                        {% icon "info" height="16px" width="16px" %} 
                                                    </button>
                                                </a>
                                                <a href="{% url 'gestion_finance:print_receipt' object.id %}" class="btn btn-outline-secondary">
                                                    {% icon "printer" height="16px" width="16px" %} 
                                                    Reçu
                                                </a>
                                                
                                                {% endblock list-options-solde %}
                                            </div>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="20" class="text-center">Aucun enregistrement</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div> <!-- Fin des Tabs -->
            </div>
        </div>
    </div>
</div>
{% endblock content %}

gestion_finance/templates/list-finance.html
{% extends "list-style.html" %}
{% load icon %}
{% load static %}

{% block table-headers %}
<th>Dossier</th>
<th>Montant</th>
<th>Date de paiement</th>
<th>Référence</th>
{% endblock table-headers %}

{% block table-rows %}
<td>{{ object.dossier }}</td>
<td>{{ object.montant_total_a_verser }}</td>
<td>{{ object.date_paiement }}</td>
<td>{{ object.reference }}</td>
{% comment %} <td>
    <a href="{% url 'gestion_finance:paiement_detail' paiement.id %}" class="btn btn-outline-primary me-2">Détails</a>
    {% if paiement.statut == 'en_attente' %}
        <a href="{% url 'gestion_finance:valider_paiement' paiement.id %}" class="btn btn-outline-success me-2">Valider</a>
    {% endif %}
</td> {% endcomment %}

{% endblock table-rows %}

{% block other-options %}
<div class="d-flex">
    <a href="{% url 'gestion_finance:print_receipt' object.id %}" class="btn btn-outline-secondary me-3">
        {% icon "printer" height="16px" width="16px" %}
    </a>
    
</div>
{% endblock other-options %}