educ_finance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from xauth import views as xauth_views


MEDIA_ROOT = getattr (settings,"MEDIA_ROOT")
MEDIA_URL = getattr (settings,"MEDIA_URL")


urlpatterns = [
    path('', views.RedirectionView.as_view(),name='redirect'),
    path('home/', views.IndexTemplateView.as_view(),name='index-view'),
    path('admin/', admin.site.urls),
    path("import-export/", include("ie_app.urls")),
    path('login/', xauth_views.CustomLoginView.as_view(), name='user-login'),
    path('logout/', xauth_views.CustomLogoutView.as_view(), name='user-logout'),
    path("signup/", xauth_views.User2CreateView.as_view(), name="user-signup"),
    path(
        "account-activation/<uuid:pk>/set-password/",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path(
        "account-activation/<str:uidb64>/set-password/<str:token>",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path('auth/', include('xauth.urls')),
    path('parameter/', include('parameter.urls')),   
    path('management/', include('gestion_administratif.urls')), 
    path('finance/', include('gestion_finance.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

gestion_administratif/urls.py
from django.urls import path
from . import views
from gestion_administratif.views import HistoriqueDossier
from .views import StatistiquesView

app_name = "gestion_administratif"

urlpatterns = [
    path('dossiers/', views.DossierListView.as_view(), name='dossier-list'),
    path('dossiers/create/', views.DossierCreateView.as_view(), name='dossier-create'),
    path('dossiers/<uuid:pk>/', views.DossierDetailView.as_view(), name='dossier-detail'),
    path('dossiers/<uuid:pk>/update/', views.DossierUpdateView.as_view(), name='dossier-update'),
    path('dossiers/<uuid:pk>/delete/', views.DossierDeleteView.as_view(), name='dossier-delete'),
    path('dossier/<uuid:pk>/<str:action>/', views.valider_ou_rejeter_dossier, name='valider_ou_rejeter_dossier'),
    path('transfert/<uuid:pk>/', views.Transfert.as_view(), name='transfert-dossier'),
    path('dossiers-transferes/', HistoriqueDossier.as_view(), name='historique-dossier'),
    
    

    path('statistiques/', StatistiquesView.as_view(), name='statistiques')
    
]

# urls.py

gestion_finance/urls.py
# gestion_finance/urls.py

from django.urls import path
from . import views
from .views import PrintReceiptView



app_name = 'gestion_finance'

urlpatterns = [
    path('other/valider/', views.ValiderPaiement, name='valider'),
    path('paiements/list', views.PaiementListView.as_view(), name='paiement-list'),
    path('paiements/create/', views.PaiementCreateView.as_view(), name='paiement-create'),
    path('paiements/<uuid:pk>/', views.PaiementDetailView.as_view(), name='paiement-detail'),
    path('paiements/<uuid:pk>/update/', views.PaiementUpdateView.as_view(), name='paiement-update'),
    path('paiements/<uuid:pk>/delete/', views.PaiementDeleteView.as_view(), name='paiement-delete'),
    
    #path('Paiement/<uuid:pk>/<str:action>/', views.valider_ou_rejeter_Paiement, name='valider_ou_rejeter_Paiement'),
    path('paiement/dossier/list', views.DossierValideListView.as_view(), name='dossier-list'),
    path('paiements/create/<uuid:pk>', views.DossierPaiementCreateView.as_view(), name='dossier-paiement'),
    path('paiements/<uuid:pk>/recu/', PrintReceiptView.as_view(), name='print_receipt'),    
]

parameter/urls.py
from django.urls import path

from parameter import views

app_name = "parameter"

urlpatterns = [
    path(
        "parameters/ufrs/list/",
        view=views.UfrListView.as_view(),
        name="ufr-list",
    ),
    path(
        "parameters/ufrs/create/",
        view=views.UfrCreateView.as_view(),
        name="ufr-create",
    ),
    path(
        "parameters/ufrs/<slug:slug>/detail/",
        view=views.UfrDetailView.as_view(),
        name="ufr-detail",
    ),
    path(
        "parameters/ufrs/<slug:slug>/update/",
        view=views.UfrUpdateView.as_view(),
        name="ufr-update",
    ),
    path(
        "parameters/ufrs/<slug:slug>/delete/",
        view=views.UfrDeleteView.as_view(),
        name="ufr-delete",
    ),
    #autre
    path(
        "parameters/departements/list/",
        view=views.DepartementListView.as_view(),
        name="departement-list",
    ),
    path(
        "parameters/departements/create/",
        view=views.DepartementCreateView.as_view(),
        name="departement-create",
    ),
    path(
        "parameters/departements/<slug:slug>/detail/",
        view=views.DepartementDetailView.as_view(),
        name="departement-detail",
    ),
    path(
        "parameters/departements/<slug:slug>/update/",
        view=views.DepartementUpdateView.as_view(),
        name="departement-update",
    ),
    path(
        "parameters/departements/<slug:slug>/delete/",
        view=views.DepartementDeleteView.as_view(),
        name="departement-delete",
    ),
    
    
    #autre
    path(
        "parameters/filieres/list/",
        view=views.FiliereListView.as_view(),
        name="filiere-list",
    ),
    path(
        "parameters/filieres/create/",
        view=views.FiliereCreateView.as_view(),
        name="filiere-create",
    ),
    path(
        "parameters/filieres/<slug:slug>/detail/",
        view=views.FiliereDetailView.as_view(),
        name="filiere-detail",
    ),
    path(
        "parameters/filieres/<slug:slug>/update/",
        view=views.FiliereUpdateView.as_view(),
        name="filiere-update",
    ),
    path(
        "parameters/filieres/<slug:slug>/delete/",
        view=views.FiliereDeleteView.as_view(),
        name="filiere-delete",
    ),
    
    #autre
    path(
        "parameters/enseignants/list/",
        view=views.EnseignantListView.as_view(),
        name="enseignant-list",
    ),
    path(
        "parameters/enseignants/create/",
        view=views.EnseignantCreateView.as_view(),
        name="enseignant-create",
    ),
    path(
        "parameters/enseignants/<uuid:pk>/detail/",
        view=views.EnseignantDetailView.as_view(),
        name="enseignant-detail",
    ),
    path(
        "parameters/enseignants/<uuid:pk>/update/",
        view=views.EnseignantUpdateView.as_view(),
        name="enseignant-update",
    ),
    path(
        "parameters/enseignants/<uuid:pk>/delete/",
        view=views.EnseignantDeleteView.as_view(),
        name="enseignant-delete",
    ),
    
    #autre
    path(
        "parameters/modules/list/",
        view=views.ModuleListView.as_view(),
        name="module-list",
    ),
    path(
        "parameters/modules/create/",
        view=views.ModuleCreateView.as_view(),
        name="module-create",
    ),
    path(
        "parameters/modules/<slug:slug>/detail/",
        view=views.ModuleDetailView.as_view(),
        name="module-detail",
    ),
    path(
        "parameters/modules/<slug:slug>/update/",
        view=views.ModuleUpdateView.as_view(),
        name="module-update",
    ),
    path(
        "parameters/modules/<slug:slug>/delete/",
        view=views.ModuleDeleteView.as_view(),
        name="module-delete",
    ),
    
#autre
    path(
        "parameters/typepaiements/list/",
        view=views.TypePaiementListView.as_view(),
        name="typepaiement-list",
    ),
    path(
        "parameters/typepaiements/create/",
        view=views.TypePaiementCreateView.as_view(),
        name="typepaiement-create",
    ),
    path(
        "parameters/typepaiements/<slug:slug>/detail/",
        view=views.TypePaiementDetailView.as_view(),
        name="typepaiement-detail",
    ),
    path(
        "parameters/typepaiements/<slug:slug>/update/",
        view=views.TypePaiementUpdateView.as_view(),
        name="typepaiement-update",
    ),
    path(
        "parameters/typepaiements/<slug:slug>/delete/",
        view=views.TypePaiementDeleteView.as_view(),
        name="typepaiement-delete",
    ),
]

xauth/urls.py
from django.urls import path

from xauth import views

app_name = "auth"

urlpatterns = [
    # User
    path("users/create/", views.UserCreateView.as_view(), name="user-create"),
    path("users/list/", views.UserListView.as_view(), name="user-list"),
    path("users/staff/list/", views.StaffListView.as_view(), name="staff-list"),
    path(
        "users/<uuid:pk>/edit/",
        views.UserUpdateView.as_view(),
        name="user-update",
    ),
    path(
        "users/<uuid:pk>/edit/photo",
        views.UserProfilePhotoUpdateView.as_view(),
        name="user-update-photo",
    ),
    path(
        "users/<uuid:pk>/detail/",
        views.UserDetailView.as_view(),
        name="user-detail",
    ),
    path(
        "users/<uuid:pk>/delete/",
        views.UserDeleteView.as_view(),
        name="user-delete",
    ),
    path(
        "users/<uuid:pk>/password/",
        views.UserUpdatePasswordView.as_view(),
        name="user-update-password",
    ),
    path(
        "users/<uuid:pk>/make-admin/",
        views.UserAdminRightView.as_view(),
        name="user-make-admin",
    ),
    path(
        "users/<uuid:pk>/send-activation-key/",
        views.UserSendSecreteKey.as_view(),
        name="user-send-key",
    ),
    # Group
    path("groups/create/", views.GroupCreateView.as_view(), name="group-create"),
    path(
        "groups/<int:pk>/update/",
        views.GroupUpdateView.as_view(),
        name="group-update",
    ),
    path("groups/list/", views.GroupListView.as_view(), name="group-list"),
    path(
        "groups/<int:pk>/delete/",
        views.GroupDeleteView.as_view(),
        name="group-delete",
    ),
    path(
        "groups/<int:pk>/detail/",
        views.GroupDetailView.as_view(),
        name="group-detail",
    ),
    # Assign
    # path(
    #     "users/nomination/<uuid:pk>/create/",
    #     views.AssignCreateView.as_view(),
    #     name="nomination-create",
    # ),
    path(
        "users/nomination/<uuid:pk>/create/",
        views.RoleCreateView.as_view(),
        name="nomination-create",
    ),
    path('activity/', views.ActivityLogView.as_view(), name='activity_log'),
]

parameter/models.py
from django.db import models

# Create your models here.

from educ_finance.cmodels import (
    ParameterModel,
    CONSTRAINT,
    CommonAbstractModel,
    AutoSlugField,
    StatusModel,
    CommonAbstractModelWithCodeModel,
)
from educ_finance.constants import MIN_LENGTH, MEDIUM_LENGTH, BIG_LENGTH

class MailContent(CommonAbstractModel):
    slug = AutoSlugField(
        populate_from="label", always_update=True, max_length=MEDIUM_LENGTH, unique=True
    )
    label = models.CharField("Libellé", max_length=MEDIUM_LENGTH, unique=True)

    class Meta:
        abstract = True





from django.db import models

class UFR(ParameterModel): 
    sigle = models.CharField(max_length=10, unique=True, verbose_name="Sigle", null=True)

    class Meta:
        ordering = ["label"]
        verbose_name = "UFR"
        verbose_name_plural = "UFRs"
        permissions = [
            ("list_ufr", "Can list ufr"),
            ("export_ufr", "Can export ufr"),
            ("import_ufr", "Can import ufr"),
            ("print_ufr", "Can print ufr"),
        ]

    def __str__(self):
        return f"{self.sigle} - {self.label}"


class Departement(ParameterModel):
    ufr = models.ForeignKey(
        UFR,
        on_delete=models.CASCADE,
        related_name="departements",  # Relation pour accéder aux départements liés à une UFR
        verbose_name="UFR associée", null=True
    )

    class Meta:
        ordering = ["label"]
        verbose_name = "Departement"
        verbose_name_plural = "Departements"
        permissions = [
            ("list_departement", "Can list departement"),
            ("export_departement", "Can export departement"),
            ("import_departement", "Can import departement"),
            ("print_departement", "Can print departement"),
        ]

    def __str__(self):
        return f"{self.label} ({self.ufr})"


class Filiere(ParameterModel):
    departement = models.ForeignKey(Departement, on_delete=models.CASCADE, related_name="filieres", verbose_name="Département associé")
    
    class Meta:
        ordering = ["label"]
        verbose_name = "Filiere"
        verbose_name_plural = "Filieres"
        permissions = [
            ("list_filiere", "Can list filiere"),
            ("export_filiere", "Can export filiere"),
            ("import_filiere", "Can import filiere"),
            ("print_filiere", "Can print filiere"),
        ]
    def __str__(self):
        return f"{self.label} ({self.departement})"

class Module(ParameterModel):  # Assurez-vous que cette classe hérite de models.Model ou d'une autre classe appropriée.
    filiere = models.ForeignKey(Filiere, on_delete=models.CASCADE, related_name="modules", verbose_name="Filière associée", null=True)
    volume = models.PositiveIntegerField(verbose_name="Volume ", null=True)
    credit = models.PositiveIntegerField(verbose_name="Crédits " ,null=True)

    class Meta:
        ordering = ["label"]
        verbose_name = "Module"
        verbose_name_plural = "Modules"
        permissions = [
            ("list_module", "Can list module"),
            ("export_module", "Can export module"),
            ("import_module", "Can import module"),
            ("print_module", "Can print module"),
        ]

    def __str__(self):
        return f"{self.label} ({self.code})"

from django.db import models

from django.db import models

class Enseignant(CommonAbstractModel):
    nom = models.CharField(max_length=100, verbose_name="Nom")
    prenom = models.CharField(max_length=100, verbose_name="Prénom")
    email = models.EmailField(unique=True, verbose_name="Email")
    departement = models.ForeignKey(
        Departement,
        on_delete=models.SET_NULL,
        null=True,
        related_name="enseignants",
        verbose_name="Département associé"
    )
    ufr = models.ForeignKey(
        UFR,
        on_delete=models.CASCADE,
        related_name="enseignants",
        verbose_name="UFR associée",
        null=True
    )
    matricule = models.PositiveIntegerField(verbose_name="Numéro Matricule", null=True, blank=True)
    is_vacataire = models.BooleanField(default=False, verbose_name="Est Vacataire")  # Indicateur pour vacataire
    
    # Champ pour les grades avec des choix prédéfinis
    GRADE_CHOICES = [
        ('ingenieur', "Ingénieur"),
        ('assistant', "Assistant"),
        ('maitre_assistant', "Maître Assistant"),
        ('maitre_conference', "Maître de Conférences"),
        ('professeur', "Professeur Titulaire"),
    ]
    grade = models.CharField(
        max_length=20,
        choices=GRADE_CHOICES,
        default='assistant',
        verbose_name="Grade", null=True
    )

    class Meta:
        ordering = ["nom"]
        verbose_name = "Enseignant"
        verbose_name_plural = "Enseignants"
        permissions = [
            ("list_enseignant", "Can list enseignant"),
            ("export_enseignant", "Can export enseignant"),
            ("import_enseignant", "Can import enseignant"),
            ("print_enseignant", "Can print enseignant"),
        ]
    
    def __str__(self):
        return f"{self.prenom} {self.nom} - {self.get_grade_display()} ({self.departement})"

    def get_name(self):
        return f"{self.prenom} {self.nom}"

    def get_grade(self):
        """Retourne le grade de l'enseignant en texte lisible."""
        return self.get_grade_display()


class TypePaiement(ParameterModel):
    actif = models.BooleanField(default=True, verbose_name="Actif")

    class Meta:
        verbose_name = "Type de Paiement"
        verbose_name_plural = "Types de Paiement"
    
    def __str__(self):
        return self.label

educ_finance/templates/bases/base.html
{% load static %}
{% load icon %}


<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>E-F - Educ-Finance </title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="./images/favicon.png">
    <link rel="stylesheet" href="{% static './vendor/owl-carousel/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static './vendor/owl-carousel/css/owl.theme.default.min.css'%}">
    <link href="{% static './vendor/jqvmap/css/jqvmap.min.css'%}" rel="stylesheet">
    <link href="{% static './css/style.css'%}" rel="stylesheet">
    <link href="{% static 'formset/css/bootstrap5-extra.css' %}" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    {% block stylesheet %}{% endblock stylesheet %}

</head>

<body>

   
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
  
      
    
    <div id="main-wrapper">
       
       
       {% include "bases/header.html" %}
        {% include "bases/sidebar.html" %}

      
        <div class="content-body">
            <div class="container-fluid">
               {% block breadcrumb %}
               {% endblock breadcrumb %}

               {% include "components/alert.html" %}

               {%  block content %}
               {%  endblock content %}
    
            </div>
         </div>
        <div class="footer">
            <div class="copyright">
                <p>Copyright © Designed &amp; Developed by IsmaelCPR 2019</p>
                <p>Distributed by IsmaelCPR</p> 
            </div>
        </div>

   </div>

    <!-- Required vendors -->
    <script src="{%static './vendor/global/global.min.js'%}" nonce='request.csp_nonce'></script>
    <script src="{% static './js/quixnav-init.js'%}" nonce='request.csp_nonce'></script>
    <script src="{% static './js/custom.min.js'%}" nonce='request.csp_nonce'></script>




    <script src="{% static './vendor/circle-progress/circle-progress.min.js'%}" nonce='request.csp_nonce'></script>

    <script src="{% static './vendor/gaugeJS/dist/gauge.min.js'%}" nonce='request.csp_nonce'></script>

    <script src="{% static './js/dashboard/dashboard-1.js'%}" nonce='request.csp_nonce'></script>
    <script type="module" src="{% static 'js/django-formset.js' %}"></script>
    <!-- Bootstrap CSS -->

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

educ_finance/templates/bases/header.html

{% load static %}

<div class="nav-header">
   <a href="#" class="brand-logo">
       <img src="{% static 'images/téléchargement.png' %}" class="h-100"/>
   </a>

   <div class="nav-control">
       <div class="hamburger">
           <span class="line"></span><span class="line"></span><span class="line"></span>
       </div>
   </div>
</div>
<div class="header">
   <div class="header-content">
       <nav class="navbar navbar-expand">
           <div class="collapse navbar-collapse">
               <!-- Ajouter ml-auto pour aligner les éléments à droite -->
               <ul class="navbar-nav ms-auto header-right">
                   <li class="nav-item dropdown notification_dropdown">
                       <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                           <i class="mdi mdi-bell"></i>
                           <div class="pulse-css"></div>
                       </a>
                       <div class="dropdown-menu dropdown-menu-right">
                           <ul class="list-unstyled">
                               <li class="media dropdown-item">
                                   <span class="success"><i class="ti-user"></i></span>
                                   <div class="media-body">
                                       <a href="#">
                                           <p><strong>Martin</strong> has added a <strong>customer</strong> Successfully
                                           </p>
                                       </a>
                                   </div>
                                   <span class="notify-time">3:20 am</span>
                               </li>
                               <li class="media dropdown-item">
                                   <span class="primary"><i class="ti-shopping-cart"></i></span>
                                   <div class="media-body">
                                       <a href="#">
                                           <p><strong>Jennifer</strong> purchased Light Dashboard 2.0.</p>
                                       </a>
                                   </div>
                                   <span class="notify-time">3:20 am</span>
                               </li>
                               <li class="media dropdown-item">
                                   <span class="danger"><i class="ti-bookmark"></i></span>
                                   <div class="media-body">
                                       <a href="#">
                                           <p><strong>Robin</strong> marked a <strong>ticket</strong> as unsolved.
                                           </p>
                                       </a>
                                   </div>
                                   <span class="notify-time">3:20 am</span>
                               </li>
                               <li class="media dropdown-item">
                                   <span class="primary"><i class="ti-heart"></i></span>
                                   <div class="media-body">
                                       <a href="#">
                                           <p><strong>David</strong> purchased Light Dashboard 1.0.</p>
                                       </a>
                                   </div>
                                   <span class="notify-time">3:20 am</span>
                               </li>
                               <li class="media dropdown-item">
                                   <span class="success"><i class="ti-image"></i></span>
                                   <div class="media-body">
                                       <a href="#">
                                           <p><strong> James.</strong> has added a<strong>customer</strong> Successfully
                                           </p>
                                       </a>
                                   </div>
                                   <span class="notify-time">3:20 am</span>
                               </li>
                           </ul>
                           <a class="all-notification" href="#">See all notifications <i
                                   class="ti-arrow-right"></i></a>
                       </div>
                   </li>
                   <li class="nav-item dropdown header-profile">
                       <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                           <i class="mdi mdi-account"></i>
                       </a>
                       <div class="dropdown-menu dropdown-menu-right">
                        <a href="{% url 'auth:user-detail' request.user.pk %}" class="dropdown-item">
                            <i class="icon-user"></i>
                            <span class="ml-2">Profile</span>
                        </a>
                        
                           <a href="{% url 'user-logout' %}" class="dropdown-item">
                               <i class="icon-key"></i>
                               <span class="ml-2">Se Déconnecter</span>
                           </a>
                       </div>
                   </li>
               </ul>
           </div>
       </nav>
   </div>
</div>

educ_finance/templates/bases/sidebar.html
{% load icon %}

<div class="quixnav">
    <div class="quixnav-scroll">
        <ul class="metismenu" id="menu">
            <li><a href="{% url 'index-view' %}" aria-expanded="false">{% icon "book" class="css-class" %}<span
                class="nav-text"> Tableau de Bord</span></a></li>
            {% if perms.xauth.access_gestion_administratif %}
            <li><a class="has-arrow" href="javascript:void()" aria-expanded="false">
                <i class="icon icon-app-store"></i><span class="nav-text">Gestion Administrative</span></a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'gestion_administratif:dossier-list' %}">Dossiers Enseignants</a></li>
                    <li><a href="{% url 'gestion_administratif:historique-dossier' %}">Etat de Paiement</a></li>
                    <li><a href="{% url 'gestion_administratif:statistiques' %}">
                        <span>Rapport</span>
                    </a></li>
                </ul>
            </li>
            {% endif %}
            {% if perms.xauth.access_gestion_finance %}
    <li>
        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
            <i class="icon icon-chart-bar-33"></i>
            <span class="nav-text">Gestion Financière</span>
        </a>
        <ul aria-expanded="false">
            <li><a href="{% url 'gestion_finance:dossier-list' %}">Dossiers Transferés</a></li>
            <li><a href="{% url 'gestion_finance:paiement-list' %}">Historique de Paiement</a></li>
            
        </ul>
    </li>
{% endif %}


            {% if perms.xauth.access_parameter %}
            <li><a class="has-arrow" href="javascript:void()" aria-expanded="false">
                {% icon "settings" class="css-class" %}&nbsp;<span class="nav-text"> Paramètres</span></a>
                <ul aria-expanded="false">
                    {% if perms.parameter.view_ufr %}
                    <li><a href="{% url 'parameter:ufr-list' %}">Liste des Ufrs</a></li>
                    {% endif %}
                    {% if perms.parameter.view_departement %}
                    <li><a href="{% url 'parameter:departement-list' %}">Liste des Départements</a></li>
                    {% endif %}
                    {% if perms.parameter.view_filiere %}
                    <li><a href="{% url 'parameter:filiere-list' %}">Liste des Filières</a></li>
                    {% endif %}
                    {% if perms.parameter.view_module %}
                    <li><a href="{% url 'parameter:module-list' %}">Liste des Modules</a></li>
                    {% endif %}
                    {% if perms.parameter.view_enseignant %}
                    <li><a href="{% url 'parameter:enseignant-list' %}"> Liste des Enseignants</a></li>
                    {% endif %}
                    {% if perms.parameter.view_typepaiement %}
                    <li><a href="{% url 'parameter:typepaiement-list' %}"> Type de Paiement</a></li>
                    {% endif %}
                </ul>
            </li>
            {% endif %}

            {% if perms.xauth.access_account %}
                <li {% if "auth" in request.path %} class="active" {% endif %}>
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        {% icon "users" class="css-class" %}<span class="nav-text">&nbsp; Gestion d'utilisateurs</span>
                    </a>
                    <ul aria-expanded="false">
                        {% if perms.xauth.list_user %}
                        <li {% if "users" in request.path %} class="active" {% endif %}>
                            <a href="{% url 'auth:user-list' %}">Les utilisateurs</a>
                        </li>
                        {% endif %}
                        {% if perms.auth.list_group %}
                        <li {% if "groups" in request.path %} class="active" {% endif %}>
                            <a href="{% url 'auth:group-list' %}">Droit d'accès</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
            {% endif %}

            {% if perms.xauth.access_account %}
            <li>
                <a href="{% url 'auth:activity_log' %}">{% icon "pocket" class="css-class" %}&nbsp;Voir les Logs</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>