educ_finance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from xauth import views as xauth_views


MEDIA_ROOT = getattr (settings,"MEDIA_ROOT")
MEDIA_URL = getattr (settings,"MEDIA_URL")


urlpatterns = [
    path('', views.RedirectionView.as_view(),name='redirect'),
    path('home/', views.IndexTemplateView.as_view(),name='index-view'),
    path('admin/', admin.site.urls),
    path("import-export/", include("ie_app.urls")),
    path('login/', xauth_views.CustomLoginView.as_view(), name='user-login'),
    path('logout/', xauth_views.CustomLogoutView.as_view(), name='user-logout'),
    path("signup/", xauth_views.User2CreateView.as_view(), name="user-signup"),
    path(
        "account-activation/<uuid:pk>/set-password/",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path(
        "account-activation/<str:uidb64>/set-password/<str:token>",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path('auth/', include('xauth.urls')),
    path('parameter/', include('parameter.urls')),   
    path('management/', include('gestion_administratif.urls')), 
    path('finance/', include('gestion_finance.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

xauth/urls.py
from django.urls import path

from xauth import views

app_name = "auth"

urlpatterns = [
    # User
    path("users/create/", views.UserCreateView.as_view(), name="user-create"),
    path("users/list/", views.UserListView.as_view(), name="user-list"),
    path("users/staff/list/", views.StaffListView.as_view(), name="staff-list"),
    path(
        "users/<uuid:pk>/edit/",
        views.UserUpdateView.as_view(),
        name="user-update",
    ),
    path(
        "users/<uuid:pk>/edit/photo",
        views.UserProfilePhotoUpdateView.as_view(),
        name="user-update-photo",
    ),
    path(
        "users/<uuid:pk>/detail/",
        views.UserDetailView.as_view(),
        name="user-detail",
    ),
    path(
        "users/<uuid:pk>/delete/",
        views.UserDeleteView.as_view(),
        name="user-delete",
    ),
    path(
        "users/<uuid:pk>/password/",
        views.UserUpdatePasswordView.as_view(),
        name="user-update-password",
    ),
    path(
        "users/<uuid:pk>/make-admin/",
        views.UserAdminRightView.as_view(),
        name="user-make-admin",
    ),
    path(
        "users/<uuid:pk>/send-activation-key/",
        views.UserSendSecreteKey.as_view(),
        name="user-send-key",
    ),
    # Group
    path("groups/create/", views.GroupCreateView.as_view(), name="group-create"),
    path(
        "groups/<int:pk>/update/",
        views.GroupUpdateView.as_view(),
        name="group-update",
    ),
    path("groups/list/", views.GroupListView.as_view(), name="group-list"),
    path(
        "groups/<int:pk>/delete/",
        views.GroupDeleteView.as_view(),
        name="group-delete",
    ),
    path(
        "groups/<int:pk>/detail/",
        views.GroupDetailView.as_view(),
        name="group-detail",
    ),
    # Assign
    # path(
    #     "users/nomination/<uuid:pk>/create/",
    #     views.AssignCreateView.as_view(),
    #     name="nomination-create",
    # ),
    path(
        "users/nomination/<uuid:pk>/create/",
        views.RoleCreateView.as_view(),
        name="nomination-create",
    ),
    path('activity/', views.ActivityLogView.as_view(), name='activity_log'),
]

xauth/views.py
from datetime import date

from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group
from django.contrib.auth import views as auth_views
from django.forms import BaseModelForm
from django.http.response import HttpResponse as HttpResponse
from django.utils import timezone
from django.contrib.auth import login as auth_login
from django.core.exceptions import ImproperlyConfigured, PermissionDenied
from django.db.models import Q, Sum, Max
from django.db import transaction
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from formset.views import FormViewMixin, FormView
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.crypto import get_random_string
# from web.mails import mail_password
from educ_finance import views as cviews
from xauth import forms
from xauth import models


# Create your views here.

GENERATED_PASSWORD_LENGTH = getattr(settings, "GENERATED_PASSWORD_LENGTH", 10)
DEFAULT_FROM_EMAIL = getattr(settings, "DEFAULT_FROM_EMAIL")

# Users management


def has_permission_to_give_opinion(user):
    if hasattr(user, "assign") and user.assign:
        if user.assign.group_assign.name == "DRH":
            return True
    return False


def has_permission_to_validate(user):
    if hasattr(user, "assign") and user.assign:
        if user.assign.group_assign.name == "DRH":
            return True
    return False


@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.can_assign", raise_exception=True),
    name="dispatch",
)
class AssignCreateView(cviews.CustomCreateView):
    model = models.Assign
    name = "nomination"
    form_class = forms.AssignForm
    success_url = reverse_lazy("auth:user-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(models.User, pk=self.kwargs.get(self.pk_url_kwarg))
        card_title = (
            f"Nomination du {user.grade.label} {user.get_full_name()}"
            if user.grade
            else f"Nomination de {user.get_full_name()}"
        )
        context["card_title"] = card_title
        return context

    def form_valid(self, form):
        office = form.cleaned_data["group_assign"]
        user = get_object_or_404(models.User, pk=self.kwargs.get(self.pk_url_kwarg))
        form.instance.user = user
        form.instance.assigner = self.request.user

        print("hello", office.permissions.all())

        for permission in office.permissions.all():
            user.groups.add(permission)

        return super().form_valid(form)


@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.can_assign", raise_exception=True),
    name="dispatch",
)
class RoleCreateView(cviews.CustomCreateView):
    model = models.Assign
    name = "nomination"
    form_class = forms.RoleForm
    success_url = reverse_lazy("auth:user-list")

    def dispatch(self, request, *args, **kwargs):
        self.current_user = get_object_or_404(
            models.User, pk=self.kwargs.get(self.pk_url_kwarg)
        )
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.current_user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        card_title = (
            f"Attribution d'un rôle {self.current_user.get_full_name()}"
        )
        context["card_title"] = card_title
        return context

    def form_valid(self, form):
        office = form.cleaned_data["group_assign"]
        form.instance.user = self.current_user
        form.instance.assigner = self.request.user
        self.current_user.groups.add(office)
        return super().form_valid(form)


@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.can_assign", raise_exception=True),
    name="dispatch",
)
class AssignUpdateView(cviews.CustomUpdateView):
    model = models.Assign
    name = "nomination"
    form_class = forms.AssignForm
    success_url = reverse_lazy("auth:user-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(models.User, pk=self.kwargs.get(self.pk_url_kwarg))
        context["card_title"] = (
            f"Nomination du {user.grade.label} {user.get_full_name()}"
        )
        return context

    def form_valid(self, form):
        office = form.cleaned_data["office"]
        user = get_object_or_404(models.User, pk=self.kwargs.get(self.pk_url_kwarg))
        form.instance.user = user
        form.instance.assigner = self.request.user
        user.groups.add(office.permissions)
        return super().form_valid(form)


@method_decorator(transaction.atomic, name="get")
@method_decorator(
    permission_required("xauth.can_assign", raise_exception=True),
    name="dispatch",
)
class RemoveAssignView(View):
    def get(self, request, *args, **kwargs):
        user = get_object_or_404(models.User, pk=self.kwargs.get("pk"))

        if not hasattr(user, "assign"):
            messages.error(request, "Aucune nomination pour cette utilisateur")
            return redirect("xauth:user-list")

        assign = user.assign
        assign.unassigner = request.user
        assign.end_date = timezone.now()
        assign.save()

        user.groups.remove(**assign.office.permissions)
        user.assign.remove()
        models.HistoricalAssign.objects.create(assign=assign)

        messages.error(request, "Nomination retirer avec succès")
        return redirect("xauth:user-list")


@method_decorator(
    permission_required("xauth.list_user", raise_exception=True),
    name="dispatch",
)
class UserListView(cviews.CustomListView):
    model = models.User
    name = "user"
    template_name = "private/list-user.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["can_assign"] = self.request.user.has_perm("change_right_user")
        context["deactivate_user"] = self.request.user.has_perm("deactivate_user")
        # context["can_delete"] = False
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by("first_name", "last_name")

        if hasattr(self.request.user, "assign"):
            queryset = queryset.filter(
                structure__in=self.request.user.assign.structure.get_children()
            )

        return queryset


@method_decorator(
    permission_required("xauth.list_user", raise_exception=True),
    name="dispatch",
)
class StaffListView(cviews.CustomListView):
    model = models.User
    name = "user"
    template_name = "private/list-staff.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["can_assign"] = self.request.user.has_perm("change_right_user")
        context["deactivate_user"] = self.request.user.has_perm("deactivate_user")
        context["card_title"] = "Liste du personnel militaire"
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by("first_name", "last_name")

        if hasattr(self.request.user, "assign"):
            queryset = queryset.filter(
                structure__in=self.request.user.assign.structure.get_children(),
                structure__isnull=False,
            )

        return queryset


@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.add_user", raise_exception=True),
    name="dispatch",
)
class UserCreateView(cviews.CustomCreateView):
    model = models.User
    success_url = reverse_lazy("auth:user-list")
    form_class = forms.UserCreateForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["card_title"] = "Ajout d'un nouvel utilisateur"
        return context

    def form_valid(self, form):
        while True:
                random_username = f"N{get_random_string(8)}"
                if not models.User.objects.filter(username=random_username).exists():
                    form.instance.username = random_username
                    break
        return super().form_valid(form)


@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.change_user", raise_exception=True),
    name="dispatch",
)
class UserUpdateView(cviews.CustomUpdateView):
    model = models.User
    form_class = forms.UserChangeForm

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs["user"] = self.request.user
    #     return kwargs

    def dispatch(self, request, *args, **kwargs):
        user = self.get_object()
        if request.user.is_superuser or request.user.id == user.id:
            return super().dispatch(request, *args, **kwargs)
        raise PermissionDenied

    def get_success_url(self):
        return reverse(
            "auth:user-detail", kwargs={"pk": self.kwargs.get(self.pk_url_kwarg)}
        )


@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.change_user", raise_exception=True),

xauth/templates/private/detail-group.html
{% extends "components/detail.html" %}
{% load icon %}

{% block card-title %}
{{object.name}}
{% endblock card-title %}

{% block card-description %}
{{ object.permissions.all|join:"<br>" }}
{% endblock card-description %}

{% block detail %}
{% if perms.auth.change_group  %}
<a class="btn btn-sm btn-outline-success m-1" href="{% url 'auth:group-update' object.id %}">
    {% icon "edit" height="16" width="16" %}&nbsp; Modifier
</a>
{% endif %}
{% if perms.auth.delete_group  %}
<a class="btn btn-sm btn-outline-danger m-1" href="{% url 'auth:group-delete' object.id %}">
    {% icon "trash" height="16" width="16" %}&nbsp; Supprimer
</a>
{% endif %}
{% endblock detail %}

xauth/templates/private/list-group.html
{% extends "user.html" %}

{% block table-headers %}
<th>Nom(s)</th>
<th>Permissions</th>
{% endblock table-headers %}

{% block table-rows %}
<td>{{object.name|default_if_none:"-"}}</td>
<td>{{ object.permissions.all|join:", "|truncatewords:20 }}</td>
{% endblock table-rows %}

xauth/templates/private/list-user.html
{% extends "list-style.html" %}
{% load icon %}
{% load humanize %}
{% load static %}

{% block table-headers %}
<th>Nom</th>
<th>Prénom</th>
<th>Matricule</th>
<th>Contact</th>
<th>Email</th>
<th>Rôle</th>
{% endblock table-headers %}

{% block table-rows %}
<td>{{object.last_name|title}}</td>
<td>{{object.first_name|title}}</td>
<td>{{object.matricule}}</td>
<td>{{object.phone}}</td>
<td>{{object.email}}</td>
<td>{{object.get_role}}</td>
{% endblock table-rows %}

{% block other-options %}
{% if deactivate_user %}
{% if object.is_active %}
<a class="btn btn-outline-secondary btn-sm" data-bs-toggle="popover" data-bs-content="Compte déjà activé" data-bs-container="body" style="font-size: {{ option_size }}px;">
  {% icon "key" %}
</a>
{% else %}
<a href="{% url 'auth:user-send-key' object.id %}" class="btn btn-outline-secondary btn-sm" data-bs-toggle="popover" data-bs-content="Activer le compte" data-bs-container="body" data-bs-placement="top" style="font-size: {{ option_size }}px;">
  {% icon "key" %}
</a>

{% endif %}
{% endif %}
{% if can_assign %}
{% if object.is_superuser or object.assign %}
<a href="{% url 'auth:nomination-create' object.id %}" class="btn btn-outline-info btn-sm" data-bs-toggle="tooltip" title="Donner un rôle">
  <span class="text-warning" data-bs-toggle="popover" data-bs-content="Donner un rôle" 
      data-bs-container="body" data-bs-placement="top" style="font-size: {{ option_size }}px;">
      {% icon "briefcase" %}
  </span>
</a>
{% else %}
<a href="{% url 'auth:nomination-create' object.id %}" class="btn btn-outline-info btn-sm" data-bs-toggle="tooltip" title="Donner un rôle">
  <span class="text-warning" data-bs-toggle="popover" data-bs-content="Donner un rôle" 
      data-bs-container="body" data-bs-placement="top" style="font-size: {{ option_size }}px;">
      {% icon "briefcase" %}
  </span>
</a>

{% endif %}
{% endif %}
{% endblock other-options %}

xauth/templates/private/log.html
{% extends "list-style.html" %}
{% load icon %}
{% load humanize %}
{% load static %}



{% block table-headers %}
<th>Utilisateur </th>
<th>Système d'exploitation</th>
<th>Adresse Ip</th>
<th>Date</th>
<th>Action</th>
<th>User agent</th>
{% endblock table-headers %}
{% block table-rows %}
<td>{{ object.user}}</td>
<td>{{ object.os}}</td>
<td>{{ object.ip_address}}</td>
<td>{{ object.timestamp}}</td>
<td>{{ object.action}}</td>
<td>{{ object.user_agent}}</td>
{% endblock table-rows %}

xauth/templates/private/user-profile-admin-view.html
{% extends "bases/base.html" %}
{% load static %}
{% load icon %}

{% block title %}Profil de {{ object.get_full_name }}{% endblock title %}

{% block breadcrumb %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h2>{{card_title}}</h2>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">{{ list_of }}</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">{{ card_title }}</a></li>
        </ol>
    </div>
</div>
{% endblock breadcrumb %}

{% block content %}
<div class="container my-5">
    <div class="row">
        <!-- Profile Section -->
        <div class="col-lg-4 mb-4">
            <div class="card shadow-sm">
                <div class="card-body text-center">
                    <div class="profile-header bg-primary text-white p-4 rounded-top">
                        <h5 class="mb-0">{{object.get_full_name|title}}</h5>
                        <small>{{object.grade.label|title}}</small>
                    </div>
                    <div class="mt-3">
                        {% if object.photo %}
                        <img src="{{object.photo.url}}" class="img-thumbnail rounded-circle" alt="Photo de profil" width="150">
                        {% else %}
                        <img src="{% static 'images/avatar1.png' %}" class="img-thumbnail rounded-circle" alt="Photo de profil" width="150">
                        {% endif %}
                    </div>
                    <div class="mt-3">
                        <p class="font-weight-bold">{{object.matricule|upper}}</p>
                        <p><i class="bi bi-telephone"></i> {{object.phone}}</p>
                    </div>
                </div>
            </div>
            
            <!-- Skills and Training Section -->
            {% comment %} <div class="card mt-4">
                <div class="card-header bg-secondary text-white">
                    <ul class="nav nav-pills card-header-pills justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link active" data-bs-toggle="tab" href="#competences">Compétences</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-bs-toggle="tab" href="#stages">Stages de Perfectionnement</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body tab-content">
                    <div class="tab-pane fade show active" id="competences">
                        <p>
                            Administrateur de plateforme universitaire, en charge de la gestion et de la maintenance des systèmes numériques d'apprentissage, tout en offrant un support technique aux utilisateurs.
                        </p>
                    </div>
                    <div class="tab-pane fade" id="stages">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Lieu</th>
                                    <th>Période</th>
                                    <th>Formation</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Bamako</td>
                                    <td>2022-2023</td>
                                    <td><span class="badge bg-success">Tankiste</span></td>
                                </tr>
                                <tr>
                                    <td>Ankara</td>
                                    <td>2022-2023</td>
                                    <td><span class="badge bg-success">Pilote TB2</span></td>
                                </tr>
                                <tr>
                                    <td>Ouagadougou</td>
                                    <td>2022-2023</td>
                                    <td><span class="badge bg-success">Tireur d'élite</span></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div> {% endcomment %}
        </div>

        <!-- Detailed Information Section -->
        <div class="col-lg-8">
            <div class="card shadow-sm">
                <div class="card-header bg-info text-white text-center">
                    <h5>Informations Personnelles</h5>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>Nom:</strong> {{ object.first_name }}</li>
                        <li class="list-group-item"><strong>Prénom(s):</strong> {{ object.last_name }}</li>
                        <li class="list-group-item"><strong>Date de naissance:</strong> {{ object.birthdate|date:"SHORT_DATE_FORMAT" }}</li>
                        <li class="list-group-item"><strong>Lieu de naissance:</strong> {{ object.birthplace }}</li>
                        <li class="list-group-item"><strong>Matricule:</strong> {{ object.matricule }}</li>
                    </ul>
                </div>
            </div>

            <div class="card shadow-sm mt-4">
                <div class="card-header bg-success text-white text-center">
                    <h5>Contact</h5>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>Email:</strong> {{ object.email }}</li>
                        <li class="list-group-item"><strong>Téléphone:</strong> {{ object.phone }}</li>
                        <li class="list-group-item"><strong>Adresse:</strong> {{ object.address }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}